In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score
from sklearn.model_selection import train_test_split

In [2]:
income_df = pd.read_csv('adult.csv', na_values='?')

In [3]:
# Удаляем строчки, где есть Null, из датасета
income_df = income_df.dropna()

In [5]:
# Выбор признаков для обучения
attributes = income_df[['age', 'workclass', 'fnlwgt', 'education', 'educational-num', 'marital-status', 'occupation', 
             'relationship', 'race', 'gender', 'capital-gain', 'capital-loss', 'hours-per-week', 'native-country']]

In [7]:
model = LogisticRegression()

In [8]:
# Применяем метод get_dummies для последующего обучения модели на всех признаках
attributes = pd.get_dummies( attributes, columns = [ 'workclass', 'education', 'marital-status', 'occupation', 
                                              'relationship', 'race', 'gender', 'native-country' ] )

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [10]:
le.fit(income_df['income'])

LabelEncoder()

In [57]:
le.transform( [ '<=50K', '>50K'] )

array([0, 1])

In [22]:
# Перевод в классы данных по уровню заработка
income_classes = pd.Series( le.transform( income_df['income'] ) )

In [25]:
# Разделение данных на тренировочную и тестовую выборки
x_train, x_test, y_train, y_test = train_test_split(attributes, income_classes, test_size=0.25)

In [26]:
# Обучение модели логистической регрессии
model.fit(x_train, y_train)

LogisticRegression()

In [35]:
predictions = model.predict_proba(x_train)
predictions

array([[0.70890173, 0.29109827],
       [0.74811676, 0.25188324],
       [0.88859312, 0.11140688],
       ...,
       [0.78992949, 0.21007051],
       [0.78138901, 0.21861099],
       [0.76377171, 0.23622829]])

In [40]:
predicted_income = model.predict(x_test)

In [41]:
predicted_income

array([1, 0, 0, ..., 0, 0, 0])

In [44]:
model.score(x_train, y_train)

0.7903644297676613

In [43]:
# Точность модели
model.score(x_test, y_test)

0.7950645674862905

In [47]:
# Точность модели
accuracy_score(y_test, predicted_income)

0.7950645674862905

# Модель SVM

In [50]:
svc = SVC()

In [51]:
# Обучение модели SVM
svc.fit(x_train, y_train)

SVC()

In [52]:
predicted_income_svc = svc.predict(x_test)
predicted_income_svc

array([0, 0, 0, ..., 0, 0, 0])

In [54]:
svc.score(x_train, y_train)

0.7894209222785706

In [55]:
# Точность модели
svc.score(x_test, y_test)

0.7924995577569433