# Домашнее задание "Производная функции нескольких аргументов".

In [74]:
import numpy as np
from scipy.optimize import approx_fprime

# Уровень 0:
# Посчитайте частные производные функций:

# 1) $f(x,y)=2x^2y^3 + 1/x + y^2x + 7$, а для этой функции также градиент в точке $(1,2)$

# 2) $f(x,y)=x^2y - sin(xy) + cos(x^2) + 6y$

In [75]:
from sympy import *
import numpy as np
import scipy.misc 
import matplotlib.pyplot as plt

In [76]:
x, y = symbols('x y')

In [ ]:
# Функция № 1

In [55]:
f_1 = 2 * x**2 * y**3 + 1/x + y**2 * x + 7

In [56]:
f_1

2*x**2*y**3 + x*y**2 + 7 + 1/x

In [39]:
f_1_diff_x = diff(f_1, x)
f_1_diff_x

4*x*y**3 + y**2 - 1/x**2

In [40]:
f_1_diff_y = diff(f_1, y)
f_1_diff_y

6*x**2*y**2 + 2*x*y

In [41]:
grad_f_1 = np.array([f_2_diff_x, f_2_diff_y])
grad_f_1

array([2*x*y - 2*x*sin(x**2) - y*cos(x*y), x**2 - x*cos(x*y) + 6],
      dtype=object)

In [29]:
# Найти градиент в точке (1, 2)
def func(x, *args):
    return args[0] * x[0]**2 * x[1]**3 + 1/x[0] + x[1]**2 * x[0] + 7
eps = np.sqrt(np.finfo(float).eps)
p = np.array([1., 2.])
approx_fprime(p, func, [eps, eps], 2) 

array([35.00000024, 28.00000024])

In [30]:
# Функция № 2

In [32]:
f_2 = x**2 * y - sin(x * y) + cos(x**2) + 6 * y

In [35]:
f_2_diff_x = diff(f_2, x)
f_2_diff_x

2*x*y - 2*x*sin(x**2) - y*cos(x*y)

In [37]:
f_2_diff_y = diff(f_2, y)
f_2_diff_y

x**2 - x*cos(x*y) + 6

In [38]:
grad_f_2 = np.array([f_2_diff_x, f_2_diff_y])
grad_f_2

array([2*x*y - 2*x*sin(x**2) - y*cos(x*y), x**2 - x*cos(x*y) + 6],
      dtype=object)

# Уровень 1:
# Градиентный спуск своими руками:

In [77]:
 from scipy.optimize import minimize

In [84]:
def f(x):
    return (x[0]**2) + (x[1]**2)

# f(x,y) = x**2 + y**2

In [98]:
x_0 = np.array([100, 200])
learning_rate = 0.1

In [66]:
result = minimize(f, x_0, method='nelder-mead', options={'xtol': 1e-8, 'disp': True})
result

# Совершенно не понял зачем нужна эта функция - ее результаты не сходятся никак с результатами 
# градиентного спуска вручную

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 85
         Function evaluations: 164


 final_simplex: (array([[ 3.31391559e-09, -1.82888492e-09],
       [-3.91522747e-09, -3.79451217e-09],
       [-4.97134432e-09,  7.91645290e-09]]), array([1.43268566e-17, 2.97273287e-17, 8.73844908e-17]))
           fun: 1.4326856592347756e-17
       message: 'Optimization terminated successfully.'
          nfev: 164
           nit: 85
        status: 0
       success: True
             x: array([ 3.31391559e-09, -1.82888492e-09])

In [92]:
eps = np.sqrt(np.finfo(float).eps)
x_epochs = [x_0]
grad = approx_fprime(x_0, f, [eps, eps])

print(grad)

[200. 400.]


In [100]:
print(x_0)

[1.29197811e-08 3.32901401e-08]


In [99]:
for i in range(100):
#     # Calculate gradient
    grad = approx_fprime(x_0, f, [eps, eps])
        
    # Update x with gradient
    x_0 = x_0 -learning_rate*grad
    print(x_0)

[100 200]
[ 80. 160.]
[ 80. 160.]
[ 64. 128.]
[ 64. 128.]
[ 51.2 102.4]
[ 51.2 102.4]
[40.95999756 81.92000732]
[40.95999756 81.92000732]
[32.76799316 65.53599854]
[32.76799316 65.53599854]
[26.21439819 52.42879639]
[26.21439819 52.42879639]
[20.97151794 41.94303894]
[20.97151794 41.94303894]
[16.77721558 33.55443115]
[16.77721558 33.55443115]
[13.42177277 26.84354553]
[13.42177277 26.84354553]
[10.73741837 21.47483673]
[10.73741837 21.47483673]
[ 8.5899353  17.17986984]
[ 8.5899353  17.17986984]
[ 6.87194824 13.74389572]
[ 6.87194824 13.74389572]
[ 5.49755859 10.99511662]
[ 5.49755859 10.99511662]
[4.39804688 8.79609337]
[4.39804688 8.79609337]
[3.51843748 7.03687468]
[3.51843748 7.03687468]
[2.81475    5.62949977]
[2.81475    5.62949977]
[2.25180001 4.50359979]
[2.25180001 4.50359979]
[1.80144    3.60287981]
[1.80144    3.60287981]
[1.441152   2.88230383]
[1.441152   2.88230383]
[1.15292161 2.30584307]
[1.15292161 2.30584307]
[0.92233729 1.84467446]
[0.92233729 1.84467446]
[0.7378698

In [101]:
print(f"Минимум достигается в: {x_0}")
print(f"Значение функции в минимуме: {f(x_0)}")

Минимум достигается в: [1.29197811e-08 3.32901401e-08]
Значение функции в минимуме: 1.2751541739575584e-15


# Проверка с помощью встроенной функции numpy:

In [110]:
np.gradient(x_0_np)

array([100., 100.])